### ISSUE TITLE
charset is not defined

### ISSUE THREAD

**Issue by slonkazoid** [Play-OS/PlayOS#21]
**Describe the bug**

**To Reproduce**
1. Go to 'os.playos.io'
2. Press on 'F2'
3. See error

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Single Language
 - Browser Firefox
 - Version 75.0 (64 bit)

**Additional context**
Add charset?

**Comment by FranklinWaller** [comment]
Thank you for reporting! I've fixed this in this commit: https://github.com/Play-OS/PlayOS/commit/bc58e1a0ff952e42ac6ef05e00f6dc60d8b24a94 

This will be on os.playos.io in the next deploy.
